# Generated by Django 4.0.3 on 2022-03-31 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_products_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_image',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(max_length=5000),
        ),
    ]
