# Generated by Django 4.0.3 on 2022-04-01 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products_product_image_alter_products_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_image',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
